Style/nav link
pomazkovanton/lubimovka pull request #26
Opened 2022-10-14 10:42 UTC by Ilin-Dmitry

2022-10-14 10:58 UTC, pomazkovanton requested changes

2022-10-14 10:58 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +}
нужно hover эффект добавить и прочие если есть. 
![изображение](https://user-images.githubusercontent.com/18042030/195829371-e55501f9-5f11-49f9-99f5-53fad12ea78a.png)
Сравнивай с оригеналом -> https://lubimovka.art/library

2022-10-14 10:58 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +    margin-top: 15px;
При БЭМ  нельзя задавать внешнии отступы блокам. Нужно убрать. Потом, кто будет делать футер, добавит маржины.

2022-10-14 10:58 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +  &_header {
не понятное название модификатора. Лучше сделать ключ-значение. Например _place_header и _place_footer. Да и там эффекты наведения разные. Поэтому мы решили разделить на два элемента на созвоне. Те что в header ты делаешь, а те что в футере делает другой (элемент link просто)

2022-10-14 10:58 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +  &_header {
Поэтому наверное вообще нужно избавится от модификаторов

2022-10-14 10:58 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +.nav-link {
Еще нужно предусмотреть, когда рядом с сылкой может быть иконка, например как здесь
![изображение](https://user-images.githubusercontent.com/18042030/195830645-f8ae3bb0-71a4-4519-99db-86ac012bdf05.png)
Нужно возможно flex контейнером сделать ссылку, отцентровать весь конетент и добавить gap. Тогда вставляя иконку слева или справа будет нужный отступ и центрирование и без нее ничего не сломается

2022-10-15 10:36 UTC, pomazkovanton requested changes

2022-10-15 10:36 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +  &:hover::before {
А без псевдоэлементов не получится сделать? Например вот так? 
```
.myNav {
          color: black;
          text-decoration: none;
          padding: 0px 10px;
        }

        .myNav:hover {
          border-left: 1px solid black;
          border-right: 1px solid black;
          border-radius: 100px;
        }
```
Вроде должно работать, но я не пробовал)

2022-10-15 10:36 UTC, pomazkovanton commented on styles/components/UI/nav-link.scss
> +  &_style_uppercase {
Стили связанные с флексом, я бы перенес просто в nav-link, так как иконка может у ссылки появится, а например апперкейса не будет. Тогда можно было бы сделать булевый модификатор, типа nav_upercase, который удет отвечать только за шрифт. И при этом иконку можно было бы вставлять в любую ссылку и ссылки бы не ломались)

2022-10-15 12:42 UTC, Ilin-Dmitry commented on styles/components/UI/nav-link.scss
> +  &:hover::before {
Мне не удалось подобрать нужные значения. получаются не скобки, а окружность. Думаю, вариант с ::before и ::after вполне рабочий

2022-10-15 12:42 UTC, Ilin-Dmitry commented on styles/components/UI/nav-link.scss
> +  &_style_uppercase {
Переделал

2022-10-15 13:50 UTC, merged