Style/card show
pomazkovanton/lubimovka pull request #43
Opened 2022-10-17 10:03 UTC by Ilin-Dmitry

2022-10-17 12:27 UTC, pomazkovanton requested changes

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +    <p class="card-show__description">читка проекта <br>Любимовка.Ещё
Я бы не использовал br, а сделал бы ограничение ьлока по ширине лучше

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +      <p>15 декабря</p>
Для даты и времени я бы использовал данный тэг https://doka.guide/html/time/?ysclid=l9cqeq2vbx310873231

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +      <p>15 декабря</p>
И потом в места дива обернул бы в один тэг p

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +  <img class="card-show__poster" src="./accets/images/poster-2.jpg" alt="обложка спектакля">
просто моджно написать более семантично. А то будет 20 таких элементов, а для слепого это будет 20 обложек спектакля)) https://htmlacademy.ru/blog/html/alt-text?ysclid=l9cqhk4vwt914879669

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +  &__title {
Можно сделать троеточие в конеце, если слово окажется длинее ширины контейнера https://stackoverflow.com/questions/486563/overflowhidden-dots-at-the-end
А то сейчас оно просто обрезается
![изображение](https://user-images.githubusercontent.com/18042030/196175139-97990e13-3487-4953-b8a1-b642ca4b5b06.png)

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +    a {
можно вместо этого элемента на __links навешать gap: 16px и маржин контейенеру задать) Ну и от ширины тоже можно избавится)

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +  &__authors {
Этот блок можно убрать, а испоьзовать UI элеемент text text_size_m. вроде так

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +    font-size: 36px;
Свойства шрифта нужно удалить отсюда, а использовать готовык UI элемент titlt title_size_s

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +      font-size: 20px;
убрать основные шрифтовые настройки, а использовать UI элемент text text_size_l

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +    object-fit: cover;
Я бы еще позиционирование по центру задал

2022-10-17 12:27 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
> +    object-fit: cover;
Для картинки)

2022-10-17 12:28 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +  <img class="card-show__poster" src="./accets/images/poster-2.jpg" alt="обложка спектакля">
Например девушка у микрофона на черном фоне)

2022-10-17 13:34 UTC, Ilin-Dmitry commented on styles/components/card-show/card-show.html
> +      <p>15 декабря</p>
вместо <div> использовал <time>. <p> здесь не получится, нужен flex с space-between. <time> позволяет использовать flex внутри.

2022-10-17 13:36 UTC, Ilin-Dmitry commented on styles/components/card-show/card-show.html
> +      <p>15 декабря</p>
вместо div использовал time.
тег p здесь не получится, нужен flex с space-between. Time позволяет использовать flex внутри.

2022-10-17 14:19 UTC, Ilin-Dmitry commented on styles/components/card-show/card-show.scss
> +    a {
маржин я задал блоку дескрипшн, раз уж там он все равно был. Gap задал. А от ширины избавиться нельзя, иначе у разных ссылок будут бордер-боттом разной длины.

2022-10-17 14:25 UTC, Ilin-Dmitry commented on styles/components/card-show/card-show.scss
> +  &__authors {
Добавил абзацам text text_size_m, убрал лишние свойства

2022-10-17 14:28 UTC, Ilin-Dmitry commented on styles/components/card-show/card-show.scss
> +    font-size: 36px;
Исправил

2022-10-18 01:56 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +    <time class="card-show__date" datetime="2022-12-15 11:00">
В тэг time нельзя вкладывать тэг p. 
![изображение](https://user-images.githubusercontent.com/18042030/196315274-908b271f-dffa-47f7-bca5-ecb37990d3f4.png)
Может так сделать? <p><time>15 декабря</time><time>11:00</time></p>

2022-10-18 01:59 UTC, pomazkovanton commented on styles/components/card-show/card-show.scss
>      p {
НУжно стараться избегать селекторов по тэгу, лучше продуюдлировать эти свойста в селекторах по классу. Если уж решили по БЭМ делать.

2022-10-18 05:51 UTC, Ilin-Dmitry commented on styles/components/card-show/card-show.html
> +    <time class="card-show__date" datetime="2022-12-15 11:00">
В p не получится обернуть, там flex используется. Поэтому оберну в div.

2022-10-18 05:55 UTC, pomazkovanton commented on styles/components/card-show/card-show.html
> +    <time class="card-show__date" datetime="2022-12-15 11:00">
Окей)

2022-10-18 07:33 UTC, merged